kind: pipeline
name: syntax
steps:
  - name: syntax-php7.3
    image: nextcloudci/php7.3:php7.3-2
    commands:
      - composer install
      - find lib/ -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
      - ./vendor/bin/parallel-lint --exclude ./vendor/ .
trigger:
  branch:
    - master
  event:
    - pull_request
    - push
---
kind: pipeline
name: jest
steps:
  - name: jest
    image: node:lts-alpine
    commands:
      - npm install
      - npm run test
trigger:
  branch:
    - master
  event:
    - pull_request
    - push
